name: Build Wasm, add versioned .wasm on GH, add attestation to Stellar.Expert

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Environment gate
  approve-release:
    runs-on: ubuntu-latest
    environment: publish-contract
    permissions: { }
    steps:
      - run: echo "Approved release"

  release-contract:
    needs: approve-release
    permissions:
      id-token: write      # OIDC token for build-provenance attestation
      contents: write      # in order to create releases
      attestations: write
    name: Compile Stellar smart contract for production and create release
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@88068ec50cba931a96436869727ed08edeb76ade
    with:
      release_name: ${{ github.ref_name }}
      release_description: "Registry contract release"
      home_domain: 'rgstry.xyz'
      relative_path: 'contracts/registry'
      package: 'registry'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
